// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Aboves.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerAbovesTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "aboves",
    {
      description: `Look up organizational hierarchy levels above units — regions, divisions, areas, districts, or any custom grouping configured in the academy. Use this for org hierarchy above the unit level. For units themselves (stores, locations, departments), use the units tool instead.

Sub-actions:
- list: List all Above Units with optional filtering by type or search term. Supports pagination.
- get: Get details of a single Above Unit by ID, including name, type, external ID, and parent information.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "get"]).describe("The sub-action to perform: 'list' to browse Above Units, 'get' to retrieve a single Above Unit by ID"),
    type_id: z.number().int().describe("Filter Above Units by Type ID (e.g. 328339). Use the types tool to discover available type IDs. Used with list action.").optional(),
    search: z.string().describe("Search by Above Unit title (e.g. 'New York'). Partial match supported. Used with list action.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list action.").optional(),
    limit: z.number().int().describe("Number of Above Units to return per request. Default: 100, max: 100000. Used with list action.").optional(),
    aboveId: z.number().int().describe("Above Unit ID (e.g. 1286994). Required for: get. Set external_id=true if passing an external ID instead of the internal numeric ID.").optional(),
    external_id: z.boolean().describe("When true, treats aboveId as an external ID instead of the internal Schoox ID. Default: false. Used with get action.").optional(),
      },
    },
    createToolHandler("aboves", routes["aboves"], client, config),
  );
}
