// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Badges.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerBadgesTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "badges",
    {
      description: `List available badges configured in the academy. Use this to see what badges exist and their definitions. To see badges earned by a specific user, use the users tool with the get_badges action instead.

Sub-actions:
- list: List all badges of a given type (platform, group, or academy-created badges).

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list"]).describe("The sub-action to perform: 'list' to retrieve available badges"),
    badge_type: z.enum(["schoox", "group", "academy"]).describe("Badge category filter: 'schoox' (platform-default badges), 'group' (group-level badges), or 'academy' (custom academy-created badges). Default: 'schoox'.").optional(),
      },
    },
    createToolHandler("badges", routes["badges"], client, config),
  );
}
