// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Content.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerContentTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "content",
    {
      description: `Browse content items (web resources, uploaded files, SCORM packages) and related metadata such as categories, venues, and timezones. Use this for browsing all content types and content metadata. For course-specific data (skills, students, lectures, exams), use the courses tool instead.

Sub-actions:
- list: List content items with filtering by type, sub-type, category, tags, or search term. Supports pagination and sorting.
- list_categories: List content categories configured in the academy. Useful for discovering category IDs to filter content.
- list_venues: List venues (physical locations for events). Supports pagination and search.
- list_timezones: List available timezones for scheduling.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "list_categories", "list_venues", "list_timezones"]).describe("The sub-action to perform: 'list' for content items, 'list_categories' for content categories, 'list_venues' for venues, 'list_timezones' for timezones"),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list and list_venues actions.").optional(),
    limit: z.number().int().describe("Number of items to return per request. Default: 20, max: 20. Used with list and list_venues actions.").optional(),
    order_by: z.enum(["title", "time_added", "time_modified"]).describe("Sort field for content items: 'title', 'time_added', or 'time_modified'. Default: 'time_added'. Used with list action.").optional(),
    direction: z.enum(["asc", "desc"]).describe("Sort direction: 'asc' (ascending) or 'desc' (descending). Default: 'desc'. Used with list action.").optional(),
    category_id: z.number().int().describe("Filter content items by category ID (e.g. 1703). Use list_categories to discover available IDs. Used with list action.").optional(),
    type_id: z.enum(["1", "2"]).describe("Content type filter: '1' = Web Resources, '2' = Files. Used with list action.").optional(),
    sub_type_id: z.enum(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]).describe("Content sub-type filter: 1=Online Video, 2=Online Document, 3=Online Article, 4=Online Photo, 5=Academic Link, 6=Website, 7=Document, 8=Video, 9=Image, 10=Audio, 11=SCORM. Used with list action.").optional(),
    tags: z.string().describe("Filter content items by tags (e.g. 'managers' or 'Tag1,Tag2' for multiple). Used with list action.").optional(),
    search: z.string().describe("Search content items by name (e.g. 'Safety Training'). Used with list and list_categories actions.").optional(),
      },
    },
    createToolHandler("content", routes["content"], client, config),
  );
}
