// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Courses.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerCoursesTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "courses",
    {
      description: `Query the course catalog, course details, and course-related data including skills, students, lectures, exams, coupons, and invitations. Use this for course metadata, catalogs, and course-level data. For a specific user's course progress and completion status, use the dashboard tool with get_user_courses action. For browsing all content types (not just courses), use the content tool.

Sub-actions:
- list: Search and filter the course catalog. Paginated.
- list_user_courses: List courses for a specific user. Requires userId. Paginated.
- list_categories: List course categories configured in the academy.
- get: Get full details of a single course. Requires courseId.
- get_skills: List skills taught by a course. Requires courseId.
- get_students: List students enrolled in a course. Requires courseId. Paginated.
- get_lectures: List lectures within a course. Requires courseId.
- get_exams: List exams within a course. Requires courseId.
- get_coupons: List coupons for a course. Requires courseId.
- get_coupon: Get a specific coupon. Requires courseId and couponId.
- get_invitations: List invitations for a course. Requires courseId.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list_user_courses", "list_categories", "get", "get_skills", "get_students", "get_lectures", "get_exams", "get_coupons", "get_coupon", "get_invitations", "list"]).describe("The sub-action to perform: 'list' for catalog, 'get' for course details, 'list_user_courses' for a user's courses, etc."),
    userId: z.string().describe("User ID. Required for: list_user_courses. Set external_id=true if passing an external ID.").optional(),
    external_id: z.boolean().describe("When true, treats userId as an external system ID instead of Schoox internal ID. Default: false. Used with list_user_courses.").optional(),
    role: z.string().describe("Filter students by role: student, professor, or dropped_out. Used with get_students.").optional(),
    status: z.enum(["active", "archived"]).describe("Course status filter: active or archived. Default: active. Used with list.").optional(),
    search: z.string().describe("Search courses by name (e.g. 'Safety Training'). Used with list.").optional(),
    category_id: z.number().int().describe("Course category ID (e.g. 1703). Use list_categories to discover available IDs. Used with list.").optional(),
    language: z.enum(["aa", "ab", "ae", "af", "ak", "am", "an", "ar", "as", "av", "ay", "az", "ba", "be", "bg", "bh", "bi", "bm", "bn", "bo", "br", "bs", "ca", "ce", "ch", "co", "cr", "cs", "cu", "cv", "cy", "da", "de", "dv", "dz", "ee", "el", "en", "eo", "es", "et", "eu", "fa", "ff", "fi", "fj", "fo", "fr", "fy", "ga", "gd", "gl", "gn", "gu", "gv", "ha", "he", "hi", "ho", "hr", "ht", "hu", "hy", "hz", "ia", "id", "ie", "ig", "ii", "ik", "io", "is", "it", "iu", "ja", "jv", "ka", "kg", "ki", "kj", "kk", "kl", "km", "kn", "ko", "kr", "ks", "ku", "kv", "kw", "ky", "la", "lb", "lg", "li", "ln", "lo", "lt", "lu", "lv", "mg", "mh", "mi", "mk", "ml", "mn", "mr", "ms", "mt", "my", "na", "nb", "nd", "ne", "ng", "nl", "nn", "no", "nr", "nv", "ny", "oc", "oj", "om", "or", "os", "pa", "pi", "pl", "ps", "pt", "qu", "rm", "rn", "ro", "ru", "rw", "sa", "sc", "sd", "se", "sg", "si", "sk", "sl", "sm", "sn", "so", "sq", "sr", "ss", "st", "su", "sv", "sw", "ta", "te", "tg", "th", "ti", "tk", "tl", "tn", "to", "tr", "ts", "tt", "tw", "ty", "ug", "uk", "ur", "uz", "ve", "vi", "vo", "wa", "wo", "xh", "yi", "yo", "za", "zh", "zut"]).describe("ISO 639-1 language code to filter courses by content language (e.g. en, es, fr, de, ja, zh).").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list, list_user_courses, get_students.").optional(),
    enrolled: z.string().describe("Filter to courses user is enrolled in: true or false. Used with list_user_courses.").optional(),
    limit: z.number().int().describe("Max results per page. Used with list, list_user_courses, get_students.").optional(),
    courseId: z.number().int().describe("Schoox course ID (e.g. 327827). Required for: get, get_skills, get_students, get_lectures, get_exams, get_coupons, get_coupon, get_invitations.").optional(),
    onlyCompleted: z.boolean().describe("When true, returns only users who completed the course. Used with get_students.").optional(),
    couponId: z.number().int().describe("Coupon ID. Required for: get_coupon (used with courseId to get a specific coupon).").optional(),
    skills: z.array(z.number().int()).describe("Array of skill/metric IDs to find related courses (e.g. [101, 205]). Used with list.").optional(),
      },
    },
    createToolHandler("courses", routes["courses"], client, config),
  );
}
