// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Curriculums.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerCurriculumsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "curriculums",
    {
      description: `Query learning paths (curricula) — collections of courses that form a structured training program. Use this for learning path metadata, enrollment, and student lists. For a user's completion progress across learning paths, use the dashboard tool with get_user_curriculums action.

Sub-actions:
- list: Search and filter learning paths. Paginated.
- list_user_curriculums: List learning paths for a specific user. Requires userId. Paginated.
- get: Get full details of a single learning path. Requires curriculumId.
- get_students: List students enrolled in a learning path. Requires curriculumId. Paginated.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "list_user_curriculums", "get", "get_students"]).describe("The sub-action to perform: 'list' for catalog, 'get' for details, 'list_user_curriculums' for a user's paths, 'get_students' for enrollees"),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list, list_user_curriculums, get_students.").optional(),
    limit: z.number().int().describe("Max results per page. Used with list, list_user_curriculums, get_students.").optional(),
    status: z.enum(["active", "archived"]).describe("Learning path status: active or archived. Default: active. Used with list.").optional(),
    external_id: z.boolean().describe("When true, treats userId as an external system ID instead of Schoox internal ID. Default: false. Used with list_user_curriculums.").optional(),
    userId: z.number().int().describe("User ID. Required for: list_user_curriculums. Set external_id=true if passing an external ID.").optional(),
    anyLanguage: z.boolean().describe("When true, returns all courses regardless of language. Default: false. Used with list_user_curriculums.").optional(),
    curriculumId: z.number().int().describe("Learning path ID (e.g. 5001). Required for: get, get_students.").optional(),
    onlyCompleted: z.boolean().describe("When true, returns only users who completed the path. Used with get_students.").optional(),
    completionStartDate: z.string().describe("ISO date string (e.g. 2024-01-01). Returns users who completed after this date. Used with get_students.").optional(),
    completionEndDate: z.string().describe("ISO date string (e.g. 2024-12-31). Returns users who completed before this date. Used with get_students.").optional(),
      },
    },
    createToolHandler("curriculums", routes["curriculums"], client, config),
  );
}
