// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Dashboard.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerDashboardTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "dashboard",
    {
      description: `Training analytics and progress reporting. Get per-user training summaries, course/curriculum/exam progress, OJT status, and manager relationships. Also provides aggregate course and curriculum analytics. Use this for training progress, completions, and analytics. For entity metadata and catalogs, use the entity-specific tool instead: users (profile data), courses (course catalog/details), curriculums (learning path metadata), exams (exam catalog/scores).

Sub-actions:
User analytics:
- list_users: List users with training data. Paginated.
- get_user_summary: Training summary for one user. Requires userId.
- get_user_manager: Get a user's manager. Requires userId.
- get_user_ojts: List on-the-job training items for a user. Requires userId.
- get_user_courses: List courses a user is enrolled in with progress. Requires userId.
- get_user_curriculums: List learning paths a user is enrolled in with progress. Requires userId.
- get_user_exams: List exams a user has taken with scores. Requires userId.
Course analytics:
- list_courses: List courses with aggregate analytics. Paginated.
- get_course: Get analytics for a specific course. Requires courseId. Paginated.
- get_course_user: Get one user's progress in a specific course. Requires courseId and userId.
Curriculum analytics:
- list_curriculums: List learning paths with aggregate analytics.
- get_curriculum: Get analytics for a specific learning path. Requires curriculumId. Paginated.
- get_curriculum_user: Get one user's progress in a specific learning path. Requires curriculumId and userId.
Exam analytics:
- list_exams: List exams with aggregate analytics.
- get_exam: Get analytics for a specific exam. Requires examId. Paginated.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list_users", "get_user_ojts", "get_user_summary", "get_user_manager", "get_user_courses", "get_user_curriculums", "get_user_exams", "list_courses", "get_course", "get_course_user", "list_curriculums", "get_curriculum", "get_curriculum_user", "list_exams", "get_exam"]).describe("The sub-action to perform. User analytics: list_users, get_user_summary, get_user_manager, get_user_ojts, get_user_courses, get_user_curriculums, get_user_exams. Course/curriculum/exam analytics: list_courses, get_course, get_course_user, list_curriculums, get_curriculum, get_curriculum_user, list_exams, get_exam."),
    role: z.string().describe("Filter by user role (e.g. employee, customer). Used with list_users.").optional(),
    external_id: z.boolean().describe("When true, treats userId as an external system ID instead of Schoox internal ID. Default: false.").optional(),
    aboveId: z.number().int().describe("Filter by Above Unit ID (e.g. region/division). Used with list_users.").optional(),
    unitId: z.number().int().describe("Filter by Unit ID (e.g. store/location). Used with list_users.").optional(),
    jobId: z.number().int().describe("Filter by Job ID. Used with list_users.").optional(),
    search: z.string().describe("Search by name, email, or username. Used with list_users.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list_users, list_courses.").optional(),
    limit: z.number().int().describe("Max results per page, up to 1000. Default: 100. Used with list_users, list_courses.").optional(),
    sort: z.string().describe("Sort field for results. Used with list_users, list_courses.").optional(),
    order: z.enum(["asc", "desc"]).describe("Sort direction: asc or desc. Used with list_users, list_courses.").optional(),
    userId: z.string().describe("Schoox user ID (e.g. 12345). Required for: get_user_summary, get_user_manager, get_user_ojts, get_user_courses, get_user_curriculums, get_user_exams, get_course_user, get_curriculum_user. Set external_id=true if passing an external ID.").optional(),
    category_id: z.number().int().describe("Academy category ID to filter by. Used with get_user_courses, list_courses.").optional(),
    dropped_out: z.boolean().describe("When true, includes courses dropped by the user. Used with get_user_courses. Default: false.").optional(),
    courseId: z.number().int().describe("Course ID (e.g. 327827). Required for: get_course, get_course_user.").optional(),
    curriculumId: z.number().int().describe("Learning path ID (e.g. 5001). Required for: get_curriculum, get_curriculum_user.").optional(),
    examId: z.number().int().describe("Exam ID (e.g. 8001). Required for: get_exam.").optional(),
      },
    },
    createToolHandler("dashboard", routes["dashboard"], client, config),
  );
}
