// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Events.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerEventsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "events",
    {
      description: `Query instructor-led training (ILT) and virtual classroom (VC) events -- sessions, offerings, attendees, and attendance data. Use this for scheduled training events. ILT = in-person sessions; VC = virtual/online sessions. Both types share the same parameter patterns but use separate actions (e.g. list_ilt vs list_vc).

Sub-actions:
ILT (in-person):
- list_ilt: List ILT events with optional date/status filters. Paginated.
- get_ilt: Get details of a single ILT event. Requires eventId.
- get_ilt_offers: List session offerings for an ILT event. Requires eventId. Paginated.
- get_ilt_addOffers: List additional session offerings for an ILT event. Requires eventId. Paginated.
- get_ilt_users: List attendees of an ILT event. Requires eventId. Paginated.
- get_ilt_usersAttendanceData: Get attendance records for an ILT event. Requires eventId. Paginated.
VC (virtual):
- list_vc: List VC events with optional date/status filters. Paginated.
- get_vc: Get details of a single VC event. Requires eventId.
- get_vc_offers: List session offerings for a VC event. Requires eventId. Paginated.
- get_vc_users: List attendees of a VC event. Requires eventId. Paginated.
- get_vc_usersAttendanceData: Get attendance records for a VC event. Requires eventId. Paginated.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list_ilt", "list_vc", "get_ilt_addOffers", "get_ilt_offers", "get_ilt", "get_ilt_usersAttendanceData", "get_vc_usersAttendanceData", "get_vc_users", "get_ilt_users", "get_vc_offers", "get_vc"]).describe("The sub-action to perform. ILT actions: list_ilt, get_ilt, get_ilt_offers, get_ilt_addOffers, get_ilt_users, get_ilt_usersAttendanceData. VC actions: list_vc, get_vc, get_vc_offers, get_vc_users, get_vc_usersAttendanceData."),
    dateStart: z.string().describe("Date filter start (e.g. 2024-01-01). Used with list_ilt, list_vc to filter events by date range.").optional(),
    dateEnd: z.string().describe("Date filter end (e.g. 2024-12-31). Used with list_ilt, list_vc to filter events by date range.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list_ilt, list_vc.").optional(),
    limit: z.number().int().describe("Max events per page. Default: 20. Used with list_ilt, list_vc.").optional(),
    status: z.enum(["active", "archived", "canceled"]).describe("Event status: active, archived, or canceled. Default: active. Used with list_ilt, list_vc.").optional(),
    eventId: z.number().int().describe("Event ID (e.g. 3001). Required for all get_ilt_* and get_vc_* actions.").optional(),
    onlyCompleted: z.boolean().describe("When true, returns only users who completed the event (includes certificate date). Used with get_ilt_users, get_vc_users.").optional(),
    search: z.string().describe("Search events by name. Used with list_ilt, list_vc.").optional(),
      },
    },
    createToolHandler("events", routes["events"], client, config),
  );
}
