// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Exams.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerExamsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "exams",
    {
      description: `Query exam metadata and student exam results/scores. Use this for exam catalogs and per-exam student scores. For a specific user's exam history across all exams, use the dashboard tool with get_user_exams action.

Sub-actions:
- list: List all exams in the academy. Paginated.
- get_students: List all students who took a specific exam with their scores. Requires examId. Paginated.
- get_student: Get one user's score for a specific exam. Requires examId and userId.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "get_students", "get_student"]).describe("The sub-action to perform: 'list' for exam catalog, 'get_students' for all scores on an exam, 'get_student' for one user's score"),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list, get_students.").optional(),
    limit: z.number().int().describe("Max students per page, up to 100. Default: 100. Used with list, get_students.").optional(),
    examId: z.number().int().describe("Exam ID (e.g. 8001). Required for: get_students, get_student.").optional(),
    userId: z.string().describe("User ID or external ID. Required for: get_student (returns one user's score for a specific exam).").optional(),
      },
    },
    createToolHandler("exams", routes["exams"], client, config),
  );
}
