// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Groups.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerGroupsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "groups",
    {
      description: `List user groups configured in the academy. Groups are used for organizing users and assigning content, courses, and learning paths to specific audiences. Use this to browse user groups and discover group IDs.

Sub-actions:
- list: List all academy groups with pagination support.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list"]).describe("The sub-action to perform: 'list' to retrieve academy groups"),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list action.").optional(),
    limit: z.number().int().describe("Number of groups to return per request. Default: 20, max: 20. Used with list action.").optional(),
      },
    },
    createToolHandler("groups", routes["groups"], client, config),
  );
}
