// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Re-generate base with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";

import { registerAbovesTool } from "./aboves.js";
import { registerBadgesTool } from "./badges.js";
import { registerContentTool } from "./content.js";
import { registerCoursesTool } from "./courses.js";
import { registerCurriculumsTool } from "./curriculums.js";
import { registerDashboardTool } from "./dashboard.js";
import { registerEventsTool } from "./events.js";
import { registerExamsTool } from "./exams.js";
import { registerGroupsTool } from "./groups.js";
import { registerJobsTool } from "./jobs.js";
import { registerSkillsTool } from "./skills.js";
import { registerTypesTool } from "./types.js";
import { registerUnitsTool } from "./units.js";
import { registerUsageTool } from "./usage.js";
import { registerUsersTool } from "./users.js";

export function registerAllTools(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  registerAbovesTool(server, client, config);
  registerBadgesTool(server, client, config);
  registerContentTool(server, client, config);
  registerCoursesTool(server, client, config);
  registerCurriculumsTool(server, client, config);
  registerDashboardTool(server, client, config);
  registerEventsTool(server, client, config);
  registerExamsTool(server, client, config);
  registerGroupsTool(server, client, config);
  registerJobsTool(server, client, config);
  registerSkillsTool(server, client, config);
  registerTypesTool(server, client, config);
  registerUnitsTool(server, client, config);
  registerUsageTool(server, client, config);
  registerUsersTool(server, client, config);
}
