// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Jobs.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerJobsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "jobs",
    {
      description: `List job roles defined in the academy (e.g. Store Manager, Cashier, Trainer). Job IDs from this tool can be used as filters in the users and skills tools to find users or skills associated with a specific role.

Sub-actions:
- list: List all job roles with optional search by title. Supports pagination.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list"]).describe("The sub-action to perform: 'list' to retrieve job roles"),
    search: z.string().describe("Search by job title (e.g. 'Manager'). Partial match supported. Used with list action.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list action.").optional(),
    limit: z.number().int().describe("Number of jobs to return per request. Default: 100. Used with list action.").optional(),
      },
    },
    createToolHandler("jobs", routes["jobs"], client, config),
  );
}
