// AUTO-GENERATED by scripts/generate-tools.ts
// Re-generate with: npm run generate

import type { RouteConfig } from "../api/types.js";

export const routes: Record<string, Record<string, RouteConfig>> = {
  "aboves": {
    "list": { path: "/aboves", paginated: true, pathParams: [] },
    "get": { path: "/aboves/{aboveId}", paginated: false, pathParams: ["aboveId"] },
  },
  "badges": {
    "list": { path: "/badges", paginated: false, pathParams: [] },
  },
  "content": {
    "list": { path: "/content", paginated: true, pathParams: [] },
    "list_categories": { path: "/content/categories", paginated: false, pathParams: [] },
    "list_venues": { path: "/content/venues", paginated: true, pathParams: [] },
    "list_timezones": { path: "/content/timezones", paginated: false, pathParams: [] },
  },
  "courses": {
    "list_user_courses": { path: "/courses/user/{userId}", paginated: true, pathParams: ["userId"] },
    "list_categories": { path: "/courses/categories", paginated: false, pathParams: [] },
    "get": { path: "/courses/{courseId}", paginated: false, pathParams: ["courseId"] },
    "get_skills": { path: "/courses/{courseId}/skills", paginated: false, pathParams: ["courseId"] },
    "get_students": { path: "/courses/{courseId}/students", paginated: true, pathParams: ["courseId"] },
    "get_lectures": { path: "/courses/{courseId}/lectures", paginated: false, pathParams: ["courseId"] },
    "get_exams": { path: "/courses/{courseId}/exams", paginated: false, pathParams: ["courseId"] },
    "get_coupons": { path: "/courses/{courseId}/coupons", paginated: false, pathParams: ["courseId"] },
    "get_coupon": { path: "/courses/{courseId}/coupons/{couponId}", paginated: false, pathParams: ["courseId","couponId"] },
    "get_invitations": { path: "/courses/{courseId}/invitations", paginated: false, pathParams: ["courseId"] },
    "list": { path: "/courses", paginated: true, pathParams: [] },
  },
  "curriculums": {
    "list": { path: "/curriculums", paginated: true, pathParams: [] },
    "list_user_curriculums": { path: "/curriculums/user/{userId}", paginated: true, pathParams: ["userId"] },
    "get": { path: "/curriculums/{curriculumId}", paginated: false, pathParams: ["curriculumId"] },
    "get_students": { path: "/curriculums/{curriculumId}/students", paginated: true, pathParams: ["curriculumId"] },
  },
  "dashboard": {
    "list_users": { path: "/dashboard/users", paginated: true, pathParams: [] },
    "get_user_ojts": { path: "/dashboard/users/{userId}/ojts", paginated: false, pathParams: ["userId"] },
    "get_user_summary": { path: "/dashboard/users/{userId}/summary", paginated: false, pathParams: ["userId"] },
    "get_user_manager": { path: "/dashboard/users/{userId}/manager", paginated: false, pathParams: ["userId"] },
    "get_user_courses": { path: "/dashboard/users/{userId}/courses", paginated: false, pathParams: ["userId"] },
    "get_user_curriculums": { path: "/dashboard/users/{userId}/curriculums", paginated: false, pathParams: ["userId"] },
    "get_user_exams": { path: "/dashboard/users/{userId}/exams", paginated: false, pathParams: ["userId"] },
    "list_courses": { path: "/dashboard/courses", paginated: true, pathParams: [] },
    "get_course": { path: "/dashboard/courses/{courseId}", paginated: true, pathParams: ["courseId"] },
    "get_course_user": { path: "/dashboard/courses/{courseId}/users/{userId}", paginated: false, pathParams: ["courseId","userId"] },
    "list_curriculums": { path: "/dashboard/curriculums", paginated: false, pathParams: [] },
    "get_curriculum": { path: "/dashboard/curriculums/{curriculumId}", paginated: true, pathParams: ["curriculumId"] },
    "get_curriculum_user": { path: "/dashboard/curriculums/{curriculumId}/users/{userId}", paginated: false, pathParams: ["curriculumId","userId"] },
    "list_exams": { path: "/dashboard/exams", paginated: false, pathParams: [] },
    "get_exam": { path: "/dashboard/exams/{examId}", paginated: true, pathParams: ["examId"] },
  },
  "events": {
    "list_ilt": { path: "/events/ilt", paginated: true, pathParams: [] },
    "list_vc": { path: "/events/vc", paginated: true, pathParams: [] },
    "get_ilt_addOffers": { path: "/events/ilt/{eventId}/addOffers", paginated: true, pathParams: ["eventId"] },
    "get_ilt_offers": { path: "/events/ilt/{eventId}/offers", paginated: true, pathParams: ["eventId"] },
    "get_ilt": { path: "/events/ilt/{eventId}", paginated: false, pathParams: ["eventId"] },
    "get_ilt_usersAttendanceData": { path: "/events/ilt/{eventId}/usersAttendanceData", paginated: true, pathParams: ["eventId"] },
    "get_vc_usersAttendanceData": { path: "/events/vc/{eventId}/usersAttendanceData", paginated: true, pathParams: ["eventId"] },
    "get_vc_users": { path: "/events/vc/{eventId}/users", paginated: true, pathParams: ["eventId"] },
    "get_ilt_users": { path: "/events/ilt/{eventId}/users", paginated: true, pathParams: ["eventId"] },
    "get_vc_offers": { path: "/events/vc/{eventId}/offers", paginated: true, pathParams: ["eventId"] },
    "get_vc": { path: "/events/vc/{eventId}", paginated: false, pathParams: ["eventId"] },
  },
  "exams": {
    "list": { path: "/exams", paginated: true, pathParams: [] },
    "get_students": { path: "/exams/{examId}/students", paginated: true, pathParams: ["examId"] },
    "get_student": { path: "/exams/{examId}/students/{userId}", paginated: false, pathParams: ["examId","userId"] },
  },
  "groups": {
    "list": { path: "/groups", paginated: true, pathParams: [] },
  },
  "jobs": {
    "list": { path: "/jobs", paginated: true, pathParams: [] },
  },
  "skills": {
    "list": { path: "/skills", paginated: true, pathParams: [] },
    "get_job": { path: "/skills/jobs/{jobId}", paginated: false, pathParams: ["jobId"] },
    "get_user": { path: "/skills/users/{userId}", paginated: false, pathParams: ["userId"] },
    "get_user_skillAssessments": { path: "/skills/{skillId}/users/{userId}/skillAssessments", paginated: false, pathParams: ["skillId","userId"] },
    "get_jobs": { path: "/skills/{skillId}/jobs", paginated: true, pathParams: ["skillId"] },
    "get_courses": { path: "/skills/{skillId}/courses", paginated: true, pathParams: ["skillId"] },
    "get_assessment": { path: "/skills/assessments/{assessmentId}", paginated: false, pathParams: ["assessmentId"] },
  },
  "types": {
    "list": { path: "/types", paginated: false, pathParams: [] },
  },
  "units": {
    "list": { path: "/units", paginated: true, pathParams: [] },
    "get": { path: "/units/{unitId}", paginated: false, pathParams: ["unitId"] },
    "list_archived": { path: "/units/archived", paginated: true, pathParams: [] },
  },
  "usage": {
    "list": { path: "/usage", paginated: false, pathParams: [] },
  },
  "users": {
    "get": { path: "/users/{userId}", paginated: false, pathParams: ["userId"] },
    "get_badges": { path: "/users/{userId}/badges", paginated: false, pathParams: ["userId"] },
    "list": { path: "/users", paginated: true, pathParams: [] },
  },
};
