// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Skills.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerSkillsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "skills",
    {
      description: `Query skill/competency definitions, skill assessments, and the relationships between skills, jobs, courses, and users. Use this for competency management. To see what skills a course teaches, use the courses tool with get_skills action. To see a user's overall training progress (not just skills), use the dashboard tool.

Sub-actions:
- list: List all skills/competencies with optional filtering by type or search term. Paginated.
- get_job: List skills required for a specific job. Requires jobId.
- get_user: Get a user's skill profile (all skills and levels). Requires userId.
- get_user_skillAssessments: Get assessment results for a user on a specific skill. Requires skillId and userId.
- get_jobs: List jobs that require a specific skill. Requires skillId. Paginated.
- get_courses: List courses that teach a specific skill. Requires skillId. Paginated.
- get_assessment: Get details of a single assessment. Requires assessmentId.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "get_job", "get_user", "get_user_skillAssessments", "get_jobs", "get_courses", "get_assessment"]).describe("The sub-action to perform: 'list' for skill catalog, 'get_job' for job skills, 'get_user' for user skill profile, 'get_user_skillAssessments' for assessment results, 'get_jobs'/'get_courses' for skill relationships, 'get_assessment' for assessment details"),
    typeId: z.number().int().describe("Filter skills by metric type ID. Used with list.").optional(),
    search: z.string().describe("Search skills by name (e.g. 'Leadership'). Used with list.").optional(),
    external_id: z.string().describe("Skill external ID (string, not a boolean flag like other tools). Used with list to filter by external identifier.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list, get_jobs, get_courses.").optional(),
    limit: z.number().int().describe("Max results per page, up to 100. Default: 100. Used with list, get_jobs, get_courses.").optional(),
    jobId: z.number().int().describe("Job ID (e.g. 201). Required for: get_job.").optional(),
    userId: z.number().int().describe("User ID (e.g. 12345). Required for: get_user, get_user_skillAssessments.").optional(),
    skillId: z.number().int().describe("Skill ID (e.g. 501). Required for: get_user_skillAssessments, get_jobs, get_courses.").optional(),
    assessmentId: z.number().int().describe("Assessment ID. Required for: get_assessment.").optional(),
      },
    },
    createToolHandler("skills", routes["skills"], client, config),
  );
}
