// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Types.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerTypesTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "types",
    {
      description: `List custom type definitions configured in the academy settings. Returns type enumerations such as Above Unit types, which define the organizational hierarchy levels. Use this to discover available type IDs that can be used as filters in other tools (e.g. type_id parameter in the aboves tool).

Sub-actions:
- list: List all configured type definitions in the academy.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list"]).describe("The sub-action to perform: 'list' to retrieve type definitions"),
      },
    },
    createToolHandler("types", routes["types"], client, config),
  );
}
