// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Units.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerUnitsTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "units",
    {
      description: `Look up organizational units (stores, locations, departments) in the academy hierarchy. Units are the lowest level of the organizational structure. Use this for units themselves. For higher-level groupings (regions, divisions, areas), use the aboves tool instead.

Sub-actions:
- list: List all active units with optional filtering by search term, parent Above Unit, or Above Unit ID. Supports pagination.
- get: Get details of a single unit by ID, including name, external ID, and organizational placement.
- list_archived: List archived (inactive) units. Supports pagination.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list", "get", "list_archived"]).describe("The sub-action to perform: 'list' for active units, 'get' for a single unit by ID, 'list_archived' for inactive units"),
    search: z.string().describe("Search by unit title (e.g. 'Chicago'). Comma-separate multiple terms (e.g. 'Chicago,Boston'). Used with list action.").optional(),
    search_above: z.string().describe("Filter units by their parent Above Unit title (e.g. 'Northeast Region'). Used with list action.").optional(),
    above_id: z.number().int().describe("Filter units by Above Unit ID (e.g. 42). Used with list action.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list and list_archived actions.").optional(),
    limit: z.number().int().describe("Number of units to return per request. Default: 100, max: 100000. Used with list and list_archived actions.").optional(),
    unitId: z.string().describe("Unit ID (e.g. '100') or external ID. Required for: get. Set external_id=true if passing an external ID instead of the internal numeric ID.").optional(),
    external_id: z.boolean().describe("When true, treats unitId as an external ID instead of the internal Schoox ID. Default: false. Used with get action.").optional(),
      },
    },
    createToolHandler("units", routes["units"], client, config),
  );
}
