// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Usage.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerUsageTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "usage",
    {
      description: `Get academy-wide usage and licensing summary statistics, including total users, active users, and license utilization. Use this for high-level academy usage stats. For per-user training data and progress details, use the dashboard tool instead.

Sub-actions:
- list: Retrieve aggregate usage data for the academy.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["list"]).describe("The sub-action to perform: 'list' to retrieve academy usage statistics"),
      },
    },
    createToolHandler("usage", routes["usage"], client, config),
  );
}
