// Originally auto-generated by scripts/generate-tools.ts, now manually maintained
// Source: ../schoox.com/docs/api/v1/Users.yml
// Re-generate with: npm run generate

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SchooxClient } from "../api/client.js";
import type { SchooxClientConfig } from "../api/types.js";
import { createToolHandler } from "./handler.js";
import { routes } from "./routes.js";

export function registerUsersTool(server: McpServer, client: SchooxClient, config: SchooxClientConfig): void {
  server.registerTool(
    "users",
    {
      description: `Look up Schoox user profiles and badges. Use this for identity data (name, email, role, organizational placement). For training progress, course completions, and analytics, use the dashboard tool instead.

Sub-actions:
- list: Search and filter users by role, org unit, job, or search term. Paginated.
- get: Get full profile for one user. Requires userId. Accepts Schoox ID, external ID (set external_id=true), or email (set is_email=true).
- get_badges: List badges earned by a user. Requires userId.

Returns JSON: { data, _meta: { tool, action, returned, truncated? } }. When truncated is true, apply filters or pagination params to narrow results.`,
      annotations: {
        readOnlyHint: true,
        destructiveHint: false,
      },
      inputSchema: {
    action: z.enum(["get", "get_badges", "list"]).describe("The sub-action to perform: 'list' for user search, 'get' for one user's profile, 'get_badges' for earned badges"),
    userId: z.union([z.number().int().min(1), z.string()]).describe("User identifier (e.g. 12345). Required for: get, get_badges. Accepts Schoox user ID, external ID (set external_id=true), or email (set is_email=true).").optional(),
    external_id: z.boolean().describe("When true, treats userId as an external system ID instead of Schoox internal ID. Default: false.").optional(),
    is_email: z.boolean().describe("When true, treats userId as an email address for lookup. Default: false.").optional(),
    role: z.enum(["employee", "customer", "instructor", "member"]).describe("Filter by user role: employee, customer, instructor, or member. Used with list.").optional(),
    past: z.boolean().describe("Include past/terminated employees. Only applies when role=employee. Default: false.").optional(),
    search: z.string().describe("Search by first name, last name, email, or username. Used with list.").optional(),
    aboveId: z.number().int().describe("Filter by Above Unit ID (e.g. region/division). Used with list.").optional(),
    unitId: z.number().int().describe("Filter by Unit ID (e.g. store/location). Used with list.").optional(),
    jobId: z.number().int().describe("Filter by Job ID. Used with list.").optional(),
    start: z.number().int().describe("Starting position for pagination (e.g. 0). Used with list.").optional(),
    limit: z.number().int().describe("Max users per page, up to 1000. Default: 100. Used with list.").optional(),
      },
    },
    createToolHandler("users", routes["users"], client, config),
  );
}
